### PR TITLE
Silence some warnings about empty conditionals

### PR DESCRIPTION
**Pull request by ketralnis**

### CODE REVIEW

**Comment by ketralnis** [comment]
before:

```
~/src/comp-cpp (master<>)$ make
g++ -c -std=c++11 -Wall -g -O2 -o obj/comp.o src/comp.cpp
g++ -MM -std=c++11 -Wall -g -O2 -MT 'obj/comp.o' src/comp.cpp > obj/comp.d
g++ -c -std=c++11 -Wall -g -O2 -o obj/renderer.o src/renderer.cpp
g++ -MM -std=c++11 -Wall -g -O2 -MT 'obj/renderer.o' src/renderer.cpp > obj/renderer.d
g++ -c -std=c++11 -Wall -g -O2 -o obj/util.o src/util.cpp
g++ -MM -std=c++11 -Wall -g -O2 -MT 'obj/util.o' src/util.cpp > obj/util.d
gcc -c -std=gnu11 -Wall -g -O3 -o obj/environment.o src/environment.c
src/environment.c:91:25: warning: if statement has empty body [-Wempty-body]
                if (system("xset -r"));
                                      ^
src/environment.c:91:25: note: put the semicolon on a separate line to silence this warning
src/environment.c:93:38: warning: if statement has empty body [-Wempty-body]
                if (system("setterm --repeat off"));
                                                   ^
src/environment.c:93:38: note: put the semicolon on a separate line to silence this warning
src/environment.c:109:22: warning: if statement has empty body [-Wempty-body]
        if (system("reset"));
                            ^
src/environment.c:109:22: note: put the semicolon on a separate line to silence this warning
src/environment.c:120:24: warning: if statement has empty body [-Wempty-body]
                if (system("xset r"));
                                     ^
src/environment.c:120:24: note: put the semicolon on a separate line to silence this warning
src/environment.c:122:37: warning: if statement has empty body [-Wempty-body]
                if (system("setterm --repeat on"));
                                                  ^
src/environment.c:122:37: note: put the semicolon on a separate line to silence this warning
src/environment.c:124:22: warning: if statement has empty body [-Wempty-body]
        if (system("clear"));
                            ^
src/environment.c:124:22: note: put the semicolon on a separate line to silence this warning
6 warnings generated.
gcc -MM -std=gnu11 -Wall -g -O3 -MT 'obj/environment.o' src/environment.c > obj/environment.d
gcc -c -std=gnu11 -Wall -g -O3 -o obj/output.o src/output.c
gcc -MM -std=gnu11 -Wall -g -O3 -MT 'obj/output.o' src/output.c > obj/output.d
g++ -o comp obj/comp.o obj/renderer.o obj/util.o obj/environment.o obj/output.o
```

after:

```
~/src/comp-cpp (master *<>)$ make
g++ -c -std=c++11 -Wall -g -O2 -o obj/comp.o src/comp.cpp
g++ -MM -std=c++11 -Wall -g -O2 -MT 'obj/comp.o' src/comp.cpp > obj/comp.d
g++ -c -std=c++11 -Wall -g -O2 -o obj/renderer.o src/renderer.cpp
g++ -MM -std=c++11 -Wall -g -O2 -MT 'obj/renderer.o' src/renderer.cpp > obj/renderer.d
g++ -c -std=c++11 -Wall -g -O2 -o obj/util.o src/util.cpp
g++ -MM -std=c++11 -Wall -g -O2 -MT 'obj/util.o' src/util.cpp > obj/util.d
gcc -c -std=gnu11 -Wall -g -O3 -o obj/environment.o src/environment.c
gcc -MM -std=gnu11 -Wall -g -O3 -MT 'obj/environment.o' src/environment.c > obj/environment.d
gcc -c -std=gnu11 -Wall -g -O3 -o obj/output.o src/output.c
gcc -MM -std=gnu11 -Wall -g -O3 -MT 'obj/output.o' src/output.c > obj/output.d
g++ -o comp obj/comp.o obj/renderer.o obj/util.o obj/environment.o obj/output.o
```

**Comment by gto76** [comment]
This way I get a warning that a return value from system call is not used, and if I assign it to some dummy variable, then I get a warning that a variable is not used...

**Comment by ketralnis** [comment]
Then maybe the fix is to check the return value and bail the program if it fails

**Comment by gto76** [comment]
But it's not that critical if it fails, since the system commands only disable key repeat and clear screen.

**Comment by gto76** [comment]
Probably just a printf with a message would be enough.

**Comment by gto76** [comment]
Anyways, thanks for info (there were no warnings on my machine). I will merge pull request and change it myself.

**Pull request merged**
